### ISSUE TITLE
UTF-8 conversion issue

### ISSUE THREAD

**Issue by sarahkadar** [roberth-k/dash-docset-terraform#4]
This is `aws_eks_node_group` for example but I'm seeing it in other ones as well.
<img width="1200" alt="Screenshot 2022-12-15 at 18 02 39" src="https://user-images.githubusercontent.com/48946/207934465-c1e0d03a-c27f-4df8-b0e9-d9d97571488f.png">

**Comment by roberth-k** [comment]
Hi @KTamas  --

Thank you for reporting this bug!

I've made some changes to make the renderer super explicit about character sets, which appears to have sorted it. The fix will be available in next week's release.

**Comment by sarahkadar** [comment]
Looks good so far, thanks again!
